---
- name: 'Install packages'
  become: true
  ansible.builtin.package:
    name: '{{ item }}'
    state: latest
  loop:
    - emacs-nox
    - fd-find
    - ripgrep
    - shellcheck
    # https://github.com/gidoichi/dotfiles/blob/68c7860161c7bfbc7b5e7e6e48be48dc22c23d5b/.doom.d/packages.el#L82
    - cmake
    - libtool-bin
    # https://github.com/gidoichi/dotfiles/blob/68c7860161c7bfbc7b5e7e6e48be48dc22c23d5b/.doom.d/inits/10_global-settings.el#L122
    - silversearcher-ag

- name: 'go install'
  ansible.builtin.shell: |
    command=$(echo "{{ item }}" | sed 's#.*/\(.*\)@.*#\1#')
    if which $command >/dev/null; then
      exit
    fi
    go install {{ item }}
    echo DONE
  register: result
  changed_when: result.stdout | length > 0
  loop:
    - golang.org/x/tools/gopls@latest
    - github.com/fatih/gomodifytags@latest
    - github.com/x-motemen/gore/cmd/gore@latest
    - golang.org/x/tools/cmd/guru@latest

- name: 'npm install'
  become: true
  ansible.builtin.shell: |
    if npm ls -g --json | jq -e --arg e '{{ item }}' '.dependencies[$e]' >/dev/null; then
      return
    fi
    npm install -g '{{ item }}'
    echo DONE
  register: result
  changed_when: result.stdout | length > 0
  loop:
    # https://github.com/gidoichi/dotfiles/blob/68c7860161c7bfbc7b5e7e6e48be48dc22c23d5b/.doom.d/inits/10_global-settings.el#L96
    - textlint
    # https://github.com/gidoichi/dotfiles/blob/68c7860161c7bfbc7b5e7e6e48be48dc22c23d5b/.textlintrc
    - textlint-rule-preset-ja-spacing
    - textlint-rule-preset-ja-technical-writing
    - textlint-rule-preset-jtf-style

- name: 'Configure Doom Emacs'
  ansible.builtin.shell: |
    "{{ ansible_env.HOME }}/.emacs.d/bin/doom" install --no-config --no-hooks --env --fonts
  register: result
  changed_when: >-
    result.stdout is not contains('Envvar file already exists, skipping') or
    result.stdout is not contains('No packages need attention')
